#!/bin/sh
# Clones repos from GitHub with language "Lean" and topic "lean4". Will need to be adjusted when there are more than 100 such repos.

curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/search/repositories\?q\=language:Lean+topic:lean4\&per_page\=100 | jq --raw-output '.items | map(.git_url) | .[]' | xargs -L 1 git clone --depth 1
